security.jwt.token.secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"

spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamknot
    username: root
    password: Ask#2811
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
